import NativeOfflineModule from "./NativeOfflineModule";
import type { OfflinePackDownloadState } from "./OfflineManager";
import type { LngLatBounds } from "../../types/LngLatBounds";

export type OfflinePackStatus = {
  /** Unique identifier (UUID) generated by native on pack creation */
  id: string;
  /** User-provided name for the pack */
  name: string;
  state: OfflinePackDownloadState;
  percentage: number;
  completedResourceCount: number;
  completedResourceSize: number;
  completedTileCount: number;
  completedTileSize: number;
  requiredResourceCount: number;
};

export interface OfflinePackMetadata {
  /** Unique identifier (UUID) generated by native on pack creation */
  id?: string;
  /** User-provided name for the pack */
  name: string;
  [key: string]: unknown;
}

type NativeOfflinePack = {
  bounds: number[];
  metadata: string;
};

export class OfflinePack {
  private pack: NativeOfflinePack;
  private parsedMetadata: OfflinePackMetadata | null;

  constructor(pack: NativeOfflinePack) {
    this.pack = pack;
    this.parsedMetadata = null;
  }

  /**
   * Gets the unique identifier (UUID) of the pack.
   * This is generated by native on pack creation and is stable across name changes.
   * Returns null if metadata is not available or id is not present (legacy packs).
   */
  get id(): string | null {
    const { metadata } = this;
    return (metadata && metadata.id) || null;
  }

  /**
   * Gets the user-provided name of the pack.
   * Returns null if metadata is not available.
   */
  get name(): string | null {
    const { metadata } = this;
    return metadata && metadata.name;
  }

  /**
   * Gets the preferred identifier for this pack.
   * Returns the UUID if available, otherwise falls back to name.
   * Use this when calling pack operations (delete, pause, resume, etc.).
   */
  get identifier(): string | null {
    return this.id || this.name;
  }

  get bounds(): LngLatBounds {
    return this.pack.bounds as LngLatBounds;
  }

  get metadata(): OfflinePackMetadata | null {
    if (!this.parsedMetadata && this.pack.metadata) {
      this.parsedMetadata = JSON.parse(this.pack.metadata);
    }
    return this.parsedMetadata;
  }

  async status(): Promise<OfflinePackStatus | null> {
    const { identifier } = this;
    if (!identifier) {
      return null;
    }
    return NativeOfflineModule.getPackStatus(
      identifier,
    ) as Promise<OfflinePackStatus>;
  }

  async resume(): Promise<void> {
    const { identifier } = this;
    if (!identifier) {
      return;
    }
    return NativeOfflineModule.resumePackDownload(identifier);
  }

  async pause(): Promise<void> {
    const { identifier } = this;
    if (!identifier) {
      return;
    }
    return NativeOfflineModule.pausePackDownload(identifier);
  }
}
