import NativeOfflineModule from "./NativeOfflineModule";
import type { OfflinePackDownloadState } from "./OfflineManager";
import type { LngLatBounds } from "../../types/LngLatBounds";

export type OfflinePackStatus = {
  /** Unique identifier (UUID) generated by native on pack creation */
  id: string;
  /** User-provided name for the pack */
  name: string;
  state: OfflinePackDownloadState;
  percentage: number;
  completedResourceCount: number;
  completedResourceSize: number;
  completedTileCount: number;
  completedTileSize: number;
  requiredResourceCount: number;
};

export interface OfflinePackMetadata {
  /** Unique identifier (UUID) generated by native on pack creation */
  id: string;
  /** User-provided name for the pack */
  name: string;
  /** User-provided metadata */
  data?: Record<string, unknown>;
}

type NativeOfflinePack = {
  bounds: number[];
  metadata: string;
};

export class OfflinePack {
  private pack: NativeOfflinePack;
  private parsedMetadata: OfflinePackMetadata | null;

  constructor(pack: NativeOfflinePack) {
    this.pack = pack;
    this.parsedMetadata = null;
  }

  /**
   * Gets the unique identifier (UUID) of the pack.
   * This is generated by native on pack creation and is stable across name changes.
   */
  get id(): string {
    const { metadata } = this;
    return metadata?.id ?? "";
  }

  /**
   * Gets the user-provided name of the pack.
   */
  get name(): string {
    const { metadata } = this;
    return metadata?.name ?? "";
  }

  /**
   * Gets the user-provided metadata for the pack.
   */
  get data(): Record<string, unknown> | undefined {
    const { metadata } = this;
    return metadata?.data;
  }

  get bounds(): LngLatBounds {
    return this.pack.bounds as LngLatBounds;
  }

  get metadata(): OfflinePackMetadata | null {
    if (!this.parsedMetadata && this.pack.metadata) {
      this.parsedMetadata = JSON.parse(this.pack.metadata);
    }
    return this.parsedMetadata;
  }

  async status(): Promise<OfflinePackStatus | null> {
    const { id } = this;
    if (!id) {
      return null;
    }
    return NativeOfflineModule.getPackStatus(id) as Promise<OfflinePackStatus>;
  }

  async resume(): Promise<void> {
    const { id } = this;
    if (!id) {
      return;
    }
    return NativeOfflineModule.resumePackDownload(id);
  }

  async pause(): Promise<void> {
    const { id } = this;
    if (!id) {
      return;
    }
    return NativeOfflineModule.pausePackDownload(id);
  }
}
