import { featureCollection, point } from "@turf/helpers";

import type { LngLatBounds } from "../../types/LngLatBounds";

export interface OfflineCreatePackInputOptions {
  name: string;
  styleURL: string;
  bounds: LngLatBounds;
  minZoom?: number;
  maxZoom?: number;
  metadata?: Record<string, unknown>;
}

export class OfflineCreatePackOptions {
  name: string;
  styleURL: string;
  bounds: string;
  minZoom: number;
  maxZoom: number;
  metadata: string;

  constructor(options: OfflineCreatePackInputOptions) {
    this.assert(options);

    this.name = options.name;
    this.styleURL = options.styleURL;
    this.bounds = this.makeBounds(options.bounds);
    this.minZoom = options.minZoom ?? 10;
    this.maxZoom = options.maxZoom ?? 20;
    this.metadata = this.makeMetadata(options.name, options.metadata);
  }

  private assert(options: OfflineCreatePackInputOptions): void {
    if (!options.styleURL) {
      throw new Error(
        "Style URL must be provided for creating an offline pack",
      );
    }

    if (!options.name) {
      throw new Error("Name must be provided for creating an offline pack");
    }

    if (!options.bounds) {
      throw new Error("Bounds must be provided for creating an offline pack");
    }
  }

  private makeBounds(bounds: LngLatBounds): string {
    const [west, south, east, north] = bounds;
    const ne: GeoJSON.Position = [east, north];
    const sw: GeoJSON.Position = [west, south];
    return JSON.stringify(featureCollection([point(ne), point(sw)]));
  }

  /**
   * Creates metadata JSON with proper structure:
   * - `name`: User-provided pack name (for display)
   * - `data`: User-provided metadata (moved to prevent interference with internal fields)
   * - `id`: UUID generated by native side on pack creation
   */
  private makeMetadata(
    name: string,
    metadata?: Record<string, unknown>,
  ): string {
    return JSON.stringify({
      name,
      data: metadata ?? {},
    });
  }
}
