import type { Layer } from "../types/Layer";
import { autoGeneratedHeader } from "../utils/autoGeneratedHeader";
import { camelCase } from "../utils/camelCase";
import { pascalCase } from "../utils/pascalCase";

const LAYER_TYPES: Record<string, string> = {
  fill: "MLNFillStyleLayer",
  "fill-extrusion": "MLNFillExtrusionStyleLayer",
  line: "MLNLineStyleLayer",
  symbol: "MLNSymbolStyleLayer",
  circle: "MLNCircleStyleLayer",
  background: "MLNBackgroundStyleLayer",
  raster: "MLNRasterStyleLayer",
  heatmap: "MLNHeatmapStyleLayer",
  hillshade: "MLNHillshadeStyleLayer",
  light: "MLNLight",
};

const PROP_NAME_OVERRIDES: Record<string, string> = Object.entries({
  "icon-allow-overlap": "icon-allows-overlap",
  "icon-image": "icon-image-name",
  "icon-ignore-placement": "icon-ignores-placement",
  "icon-keep-upright": "keeps-icon-upright",
  "icon-rotate": "icon-rotation",
  "icon-size": "icon-scale",
  "symbol-avoid-edges": "symbol-avoids-edges",
  "text-allow-overlap": "text-allows-overlap",
  "text-field": "text",
  "text-font": "text-font-names",
  "text-ignore-placement": "text-ignores-placement",
  "text-justify": "text-justification",
  "text-keep-upright": "keeps-text-upright",
  "text-max-angle": "maximum-text-angle",
  "text-max-width": "maximum-text-width",
  "text-rotate": "text-rotation",
  "text-size": "text-font-size",
  "circle-pitch-scale": "circle-scale-alignment",
  "circle-translate": "circle-translation",
  "circle-translate-anchor": "circle-translation-anchor",
  "fill-antialias": "fill-antialiased",
  "fill-translate": "fill-translation",
  "fill-translate-anchor": "fill-translation-anchor",
  "fill-extrusion-translate": "fill-extrusion-translation",
  "fill-extrusion-translate-anchor": "fill-extrusion-translation-anchor",
  "fill-extrusion-vertical-gradient": "fill-extrusion-has-vertical-gradient",
  "raster-brightness-min": "minimum-raster-brightness",
  "raster-brightness-max": "maximum-raster-brightness",
  "raster-hue-rotate": "raster-hue-rotation",
  "line-dasharray": "line-dash-pattern",
  "line-translate": "line-translation",
  "line-translate-anchor": "line-translation-anchor",
  "icon-translate": "icon-translation",
  "icon-translate-anchor": "icon-translation-anchor",
  "text-translate": "text-translation",
  "text-translate-anchor": "text-translation-anchor",
  "raster-resampling": "raster-resampling-mode",
  "text-writing-mode": "text-writing-modes",
}).reduce<Record<string, string>>((acc, [key, value]) => {
  acc[camelCase(key)] = camelCase(value);
  return acc;
}, {});

function propName(name: string) {
  if (PROP_NAME_OVERRIDES[name]) {
    return PROP_NAME_OVERRIDES[name];
  }

  return name;
}

function propMethodName(layer: Layer, name: string) {
  if (name.indexOf("Visibility") !== -1) {
    return pascalCase(layer.name) + "StyleLayer" + name;
  }

  return name;
}

function setLayerMethodName(layer: Layer) {
  return `${camelCase(layer.name)}Layer`;
}

export function renderMLRNStyleH(layers: Layer[], filePath: string): string {
  const layerMethodDecls = layers
    .map(
      (layer) =>
        `- (void)${setLayerMethodName(layer)}:(${LAYER_TYPES[layer.name as string]} *)layer withReactStyle:(NSDictionary *)reactStyle isValid:(BOOL (^)(void)) isValid;`,
    )
    .join("\n");

  const propMethodDecls = layers
    .flatMap((layer) =>
      layer.properties.flatMap((prop) => {
        const layerType = LAYER_TYPES[layer.name as string];
        const methodName = propMethodName(layer, pascalCase(prop.name));
        const decls = [
          `- (void)set${methodName}:(${layerType} *)layer withReactStyleValue:(MLRNStyleValue *)styleValue;`,
        ];
        if (prop.transition) {
          decls.push(
            `- (void)set${methodName}Transition:(${layerType} *)layer withReactStyleValue:(MLRNStyleValue *)styleValue;`,
          );
        }
        return decls;
      }),
    )
    .join("\n");

  return `// ${autoGeneratedHeader.doNotModify}
// ${autoGeneratedHeader.generatedFrom(filePath)}

#import "MLRNStyle.h"
#import "MLRNStyleValue.h"

@import MapLibre;

@interface MLRNStyle : NSObject

@property (nonatomic, strong) MLNStyle *style;

- (id)initWithMLNStyle:(MLNStyle*)mlnStyle;

${layerMethodDecls}

${propMethodDecls}

@end
`;
}

export function renderMLRNStyle(layers: Layer[], filePath: string): string {
  const dispatchMethods = layers
    .map((layer) => {
      const propCases: string[] = [];

      layer.properties.forEach((prop, i) => {
        const methodName = propMethodName(layer, pascalCase(prop.name));
        const prefix = i === 0 ? "  if" : "  } else if";

        let body: string;
        if (prop.image) {
          body = `
    if (![styleValue shouldAddImage]) {
      [self set${methodName}:layer withReactStyleValue:styleValue];
    } else {
      NSString *imageURI = [styleValue getImageURI];

      [MLRNImageLoader fetchImage:imageURI scale:[styleValue getImageScale] sdf:[styleValue getImageSdf] callback:^(NSError *error, UIImage *image) {
        if (image != nil) {
          dispatch_async(dispatch_get_main_queue(), ^{
            if (isValid()) {
              [self->_style setImage:image forName:imageURI];
              [self set${methodName}:layer withReactStyleValue:styleValue];
            }
          });
        }
      }];
    }`;
        } else {
          body = `
    [self set${methodName}:layer withReactStyleValue:styleValue];`;
        }

        propCases.push(
          `${prefix} ([prop isEqualToString:@"${prop.name}"]) {${body}`,
        );

        if (prop.transition) {
          propCases.push(
            `  } else if ([prop isEqualToString:@"${prop.name}Transition"]) {\n    [self set${methodName}Transition:layer withReactStyleValue:styleValue];`,
          );
        }
      });

      propCases.push("  } else {\n  }");

      return `- (void)${setLayerMethodName(layer)}:(${LAYER_TYPES[layer.name as string]} *)layer withReactStyle:(NSDictionary *)reactStyle isValid:(BOOL (^)(void)) isValid
{
  if (![self _hasReactStyle:reactStyle]) {
    return;
  }

  NSArray<NSString*> *styleProps = [reactStyle allKeys];
  for (NSString *prop in styleProps) {
    MLRNStyleValue *styleValue = [MLRNStyleValue make:reactStyle[prop]];

${propCases.join("\n")}
  }
}`;
    })
    .join("\n\n");

  const setterMethods = layers
    .flatMap((layer) =>
      layer.properties.flatMap((prop) => {
        const methodName = propMethodName(layer, pascalCase(prop.name));
        const layerType = LAYER_TYPES[layer.name as string];

        let body: string;
        if (layer.name === "light" && prop.name === "position") {
          body = "    layer.position = [styleValue getSphericalPosition];";
        } else if (prop.name === "visibility") {
          body = "    layer.visible = [styleValue isVisible];";
        } else {
          body = `    layer.${propName(prop.name)} = styleValue.mlnStyleValue;`;
        }

        const methods = [
          `- (void)set${methodName}:(${layerType} *)layer withReactStyleValue:(MLRNStyleValue *)styleValue
{
${body}
}`,
        ];

        if (prop.transition) {
          methods.push(
            `- (void)set${methodName}Transition:(${layerType} *)layer withReactStyleValue:(MLRNStyleValue *)styleValue
{
    layer.${propName(prop.name)}Transition = [styleValue getTransition];
}`,
          );
        }

        return methods;
      }),
    )
    .join("\n\n");

  return `// ${autoGeneratedHeader.doNotModify}
// ${autoGeneratedHeader.generatedFrom(filePath)}

#import "MLRNStyle.h"
#import "MLRNUtils.h"
#import "MLRNImageLoader.h"

@implementation MLRNStyle

- (id)initWithMLNStyle:(MLNStyle*)mlnStyle
{
    if (self = [super init]) {
        _style = mlnStyle;
    }
    return self;
}

${dispatchMethods}

${setterMethods}

- (BOOL)_hasReactStyle:(NSDictionary *)reactStyle
{
  return reactStyle != nil && reactStyle.allKeys.count > 0;
}

@end
`;
}
