import { autoGeneratedHeader } from "../utils/autoGeneratedHeader";

function jsStyleType(prop: any) {
  if (prop.type === "color" || prop.type === "colorArray") {
    return "StyleType.Color";
  }

  if (prop.type === "enum") {
    return "StyleType.Enum";
  }

  if (prop.type === "string" && prop.image) {
    return "StyleType.Image";
  }

  if (prop.type === "resolvedImage") {
    return "StyleType.Image";
  }

  if (prop.name.indexOf("Translate") !== -1) {
    return "StyleType.Translation";
  }

  return "StyleType.Constant";
}

export function render(layers: any[], filePath: string): string {
  const styleMapEntries = layers
    .map((layer: any) => {
      const entries = layer.properties
        .filter((prop: any) => prop.name !== "visibility")
        .flatMap((prop: any) => {
          const e = [`  ${prop.name}: ${jsStyleType(prop)},`];
          if (prop.transition) {
            e.push(`  ${prop.name}Transition: StyleType.Transition,`);
          }
          return e;
        });
      return entries.join("\n");
    })
    .join("\n\n");

  return `/* eslint-disable */
// ${autoGeneratedHeader.doNotModify}
// ${autoGeneratedHeader.generatedFrom(filePath)}

import { isAndroid } from './index';

const StyleType = {
  Constant: 'constant',
  Color: 'color',
  Transition: 'transition',
  Translation: 'translation',
  Function: 'function',
  Image: 'image',
  Enum: 'enum',
};

const STYLE_MAP = {
${styleMapEntries}

  visibility: StyleType.Constant,
};

const STYLE_OVERRIDES = {
  // padding
  iconTextFitPadding: {
    iosType: 'edgeinsets',
  },

  // offsets
  iconOffset: {
    iosType: 'vector',
  },
  textOffset: {
    iosType: 'vector',
  },
  lineOffset: {
    iosType: 'vector',
  },

  // translates
  fillTranslate: {
    iosType: 'vector',
  },
  lineTranslate: {
    iosType: 'vector',
  },
  iconTranslate: {
    iosType: 'vector',
  },
  textTranslate: {
    iosType: 'vector',
  },
  circleTranslate: {
    iosType: 'vector',
  },
  fillExtrusionTranslate: {
    iosType: 'vector',
  },
};

export function getStylePropertyType(styleProperty: keyof typeof STYLE_OVERRIDES): string {
  if (!isAndroid() && STYLE_OVERRIDES[styleProperty]) {
    return STYLE_OVERRIDES[styleProperty].iosType;
  }

  if (STYLE_MAP[styleProperty]) {
    return STYLE_MAP[styleProperty];
  }

  throw new Error(\`\${styleProperty} is not a valid MapLibre layer style\`);
}
`;
}
