import { autoGeneratedHeader } from "../utils/autoGeneratedHeader";
import { pascalCase } from "../utils/pascalCase";

function startAtSpace(spaceCount: number, str: string) {
  let value = "";

  for (let i = 0; i < spaceCount; i++) {
    value += " ";
  }

  return `${value}${str}`;
}

function dtsInterfaceType(prop: any) {
  const propTypes: string[] = [];

  if (prop.name.indexOf("Translate") !== -1 && prop.type !== "enum") {
    propTypes.push("Translation");
  } else if (prop.type === "color" || prop.type === "colorArray") {
    propTypes.push("string");
  } else if (prop.type === "array") {
    switch (prop.value) {
      case "number":
        propTypes.push("number[]");
        break;
      case "boolean":
        propTypes.push("boolean[]");
        break;
      case "string":
        propTypes.push("string[]");
        break;
      case "enum":
        propTypes.push(
          `(${Object.keys(prop.doc.values)
            .map((value) => `"${value}"`)
            .join(" | ")})[]`,
        );
        break;
    }
  } else if (prop.type === "number" || prop.type === "numberArray") {
    propTypes.push("number");
  } else if (prop.type === "enum") {
    propTypes.push(
      Object.keys(prop.doc.values)
        .map((value) => `"${value}"`)
        .join(" | "),
    );
  } else if (prop.type === "boolean") {
    propTypes.push("boolean");
  } else if (prop.type === "resolvedImage") {
    propTypes.push("ResolvedImageType");
  } else if (prop.type === "formatted") {
    propTypes.push("FormattedString");
  } else if (prop.type === "string") {
    propTypes.push("string");
  } else {
    console.error("Unexpected type:", prop.type);
    throw new Error(`Unexpected type: ${prop.type} for ${prop.name}`);
  }

  if (propTypes.length > 1) {
    return `${propTypes.map((p) => startAtSpace(4, p)).join(" | ")},
${startAtSpace(2, "")}`;
  } else {
    if (prop.expressionSupported) {
      let params = "";
      if (prop.expression && prop.expression.parameters) {
        params = `,[${prop.expression.parameters
          .map((v: string) => `'${v}'`)
          .join(",")}]`;
      }
      return `Value<${propTypes[0]}${params}>`;
    } else {
      return propTypes[0];
    }
  }
}

export function render(layers: any[], filePath: string): string {
  const layerInterfaces = layers
    .map((layer: any) => {
      const props = layer.properties
        .map((prop: any) => {
          const requiresPart =
            prop.doc.requires.length > 0
              ? `\n   *\n   * @requires ${prop.doc.requires.join(", ")}`
              : "";
          const disabledByPart =
            prop.doc.disabledBy.length > 0
              ? `\n   *\n   * @disabledBy ${prop.doc.disabledBy.join(", ")}`
              : "";
          let def = `  /**\n   * ${prop.doc.description}${requiresPart}${disabledByPart}\n   */\n  ${prop.name}?: ${dtsInterfaceType(prop)}`;
          if (prop.transition) {
            def += `\n  /**\n   * The transition affecting any changes to this layer's ${prop.name} property.\n   */\n  ${prop.name}Transition?: Transition,`;
          }
          return def;
        })
        .join("\n");

      return `/**\n* @deprecated\n*/\nexport interface ${pascalCase(layer.name)}LayerStyle {\n${props}\n};`;
    })
    .join("\n\n");

  const allLayerStyle = layers
    .map((l: any) => `${pascalCase(l.name)}LayerStyle`)
    .join(" | ");

  return `// ${autoGeneratedHeader.doNotModify}
// ${autoGeneratedHeader.generatedFrom(filePath)}

import { type ImageSourcePropType } from 'react-native';

export type Translation = { x: number; y: number } | [number, number];

export interface Transition {
  duration: number;
  delay: number;
}

export type FormattedString = string;

export type ExpressionName =
  // Types
  | 'array' | 'boolean' | 'collator' | 'format' | 'image' | 'literal' | 'number' | 'number-format' | 'object' | 'string'
  | 'to-boolean' | 'to-color' | 'to-number' | 'to-string' | 'typeof'
  // Feature data
  | 'accumulated' | 'feature-state' | 'geometry-type' | 'id' | 'line-progress' | 'properties'
  // Lookup
  | 'at' | 'get' | 'has' | 'in' | 'index-of' | 'length' | 'slice'
  // Decision
  | '!' | '!=' | '<' | '<=' | '==' | '>' | '>=' | 'all' | 'any' | 'case' | 'match' | 'coalesce' | 'within'
  // Ramps, scales, curves
  | 'interpolate' | 'interpolate-hcl' | 'interpolate-lab' | 'step'
  // Variable binding
  | 'let' | 'var'
  // String
  | 'concat' | 'downcase' | 'is-supported-script' | 'resolved-locale' | 'upcase'
  // Color
  | 'rgb' | 'rgba' | 'to-rgba'
  // Math
  | '-' | '*' | '/' | '%' | '^' | '+' | 'abs' | 'acos' | 'asin' | 'atan' | 'ceil' | 'cos' | 'distance' | 'e'
  | 'floor' | 'ln' | 'ln2' | 'log10' | 'log2' | 'max' | 'min' | 'pi' | 'round' | 'sin' | 'sqrt' | 'tan'
  // Zoom, Heatmap
  | 'zoom' | 'heatmap-density';

export type ExpressionField =
  | string
  | number
  | boolean
  | Expression
  | ExpressionField[]
  | { [key: string]: ExpressionField };

/**
* @deprecated
*/
export type Expression = [ExpressionName, ...ExpressionField[]];

type ExpressionParameters = 'zoom' | 'feature' | 'feature-state' | 'global-state' | 'sky-radial-progress' | 'line-progress' | 'heatmap-density';

type ResolvedImageType = ImageSourcePropType | string;

// @ts-ignore
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export type Value<T, AllowedParameters extends ExpressionParameters[] = []> =
  | T
  | Expression;

${layerInterfaces}

export type AllLayerStyle = ${allLayerStyle};
`;
}
