# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Ignore warnings except for MLRN
INHIBIT_WARNING_BY_DEFAULT = true
if INHIBIT_WARNING_BY_DEFAULT
  ORIG_POD = method(:pod)

  def pod(name, *requirements)
    options = requirements.last
    unless name == 'MapLibreReactNative'
      if options.is_a?(Hash)
        options[:inhibit_warnings] = true unless options.has_key?(:inhibit_warnings)
      else
        requirements.push({inhibit_warnings: true})
      end
    end

    ORIG_POD[name, *requirements]
  end
end

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'MapLibreReactNativeExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    $MLRN.post_install(installer)
  end
end
