/* eslint-disable */
// DO NOT MODIFY
// This file is auto-generated from scripts/templates/getStylePropertyType.ts.ejs

import { isAndroid } from "./index";

const StyleType = {
  Constant: "constant",
  Color: "color",
  Transition: "transition",
  Translation: "translation",
  Function: "function",
  Image: "image",
  Enum: "enum",
};

const STYLE_MAP = {
  fillSortKey: StyleType.Constant,
  fillAntialias: StyleType.Constant,
  fillOpacity: StyleType.Constant,
  fillOpacityTransition: StyleType.Transition,
  fillColor: StyleType.Color,
  fillColorTransition: StyleType.Transition,
  fillOutlineColor: StyleType.Color,
  fillOutlineColorTransition: StyleType.Transition,
  fillTranslate: StyleType.Translation,
  fillTranslateTransition: StyleType.Transition,
  fillTranslateAnchor: StyleType.Enum,
  fillPattern: StyleType.Image,
  fillPatternTransition: StyleType.Transition,

  lineCap: StyleType.Enum,
  lineJoin: StyleType.Enum,
  lineMiterLimit: StyleType.Constant,
  lineRoundLimit: StyleType.Constant,
  lineSortKey: StyleType.Constant,
  lineOpacity: StyleType.Constant,
  lineOpacityTransition: StyleType.Transition,
  lineColor: StyleType.Color,
  lineColorTransition: StyleType.Transition,
  lineTranslate: StyleType.Translation,
  lineTranslateTransition: StyleType.Transition,
  lineTranslateAnchor: StyleType.Enum,
  lineWidth: StyleType.Constant,
  lineWidthTransition: StyleType.Transition,
  lineGapWidth: StyleType.Constant,
  lineGapWidthTransition: StyleType.Transition,
  lineOffset: StyleType.Constant,
  lineOffsetTransition: StyleType.Transition,
  lineBlur: StyleType.Constant,
  lineBlurTransition: StyleType.Transition,
  lineDasharray: StyleType.Constant,
  lineDasharrayTransition: StyleType.Transition,
  linePattern: StyleType.Image,
  linePatternTransition: StyleType.Transition,
  lineGradient: StyleType.Color,

  symbolPlacement: StyleType.Enum,
  symbolSpacing: StyleType.Constant,
  symbolAvoidEdges: StyleType.Constant,
  symbolSortKey: StyleType.Constant,
  symbolZOrder: StyleType.Enum,
  iconAllowOverlap: StyleType.Constant,
  iconIgnorePlacement: StyleType.Constant,
  iconOptional: StyleType.Constant,
  iconRotationAlignment: StyleType.Enum,
  iconSize: StyleType.Constant,
  iconTextFit: StyleType.Enum,
  iconTextFitPadding: StyleType.Constant,
  iconImage: StyleType.Image,
  iconRotate: StyleType.Constant,
  iconPadding: StyleType.Constant,
  iconKeepUpright: StyleType.Constant,
  iconOffset: StyleType.Constant,
  iconAnchor: StyleType.Enum,
  iconPitchAlignment: StyleType.Enum,
  textPitchAlignment: StyleType.Enum,
  textRotationAlignment: StyleType.Enum,
  textField: StyleType.Constant,
  textFont: StyleType.Constant,
  textSize: StyleType.Constant,
  textMaxWidth: StyleType.Constant,
  textLineHeight: StyleType.Constant,
  textLetterSpacing: StyleType.Constant,
  textJustify: StyleType.Enum,
  textRadialOffset: StyleType.Constant,
  textVariableAnchor: StyleType.Constant,
  textAnchor: StyleType.Enum,
  textMaxAngle: StyleType.Constant,
  textWritingMode: StyleType.Constant,
  textRotate: StyleType.Constant,
  textPadding: StyleType.Constant,
  textKeepUpright: StyleType.Constant,
  textTransform: StyleType.Enum,
  textOffset: StyleType.Constant,
  textAllowOverlap: StyleType.Constant,
  textIgnorePlacement: StyleType.Constant,
  textOptional: StyleType.Constant,
  iconOpacity: StyleType.Constant,
  iconOpacityTransition: StyleType.Transition,
  iconColor: StyleType.Color,
  iconColorTransition: StyleType.Transition,
  iconHaloColor: StyleType.Color,
  iconHaloColorTransition: StyleType.Transition,
  iconHaloWidth: StyleType.Constant,
  iconHaloWidthTransition: StyleType.Transition,
  iconHaloBlur: StyleType.Constant,
  iconHaloBlurTransition: StyleType.Transition,
  iconTranslate: StyleType.Translation,
  iconTranslateTransition: StyleType.Transition,
  iconTranslateAnchor: StyleType.Enum,
  textOpacity: StyleType.Constant,
  textOpacityTransition: StyleType.Transition,
  textColor: StyleType.Color,
  textColorTransition: StyleType.Transition,
  textHaloColor: StyleType.Color,
  textHaloColorTransition: StyleType.Transition,
  textHaloWidth: StyleType.Constant,
  textHaloWidthTransition: StyleType.Transition,
  textHaloBlur: StyleType.Constant,
  textHaloBlurTransition: StyleType.Transition,
  textTranslate: StyleType.Translation,
  textTranslateTransition: StyleType.Transition,
  textTranslateAnchor: StyleType.Enum,

  circleSortKey: StyleType.Constant,
  circleRadius: StyleType.Constant,
  circleRadiusTransition: StyleType.Transition,
  circleColor: StyleType.Color,
  circleColorTransition: StyleType.Transition,
  circleBlur: StyleType.Constant,
  circleBlurTransition: StyleType.Transition,
  circleOpacity: StyleType.Constant,
  circleOpacityTransition: StyleType.Transition,
  circleTranslate: StyleType.Translation,
  circleTranslateTransition: StyleType.Transition,
  circleTranslateAnchor: StyleType.Enum,
  circlePitchScale: StyleType.Enum,
  circlePitchAlignment: StyleType.Enum,
  circleStrokeWidth: StyleType.Constant,
  circleStrokeWidthTransition: StyleType.Transition,
  circleStrokeColor: StyleType.Color,
  circleStrokeColorTransition: StyleType.Transition,
  circleStrokeOpacity: StyleType.Constant,
  circleStrokeOpacityTransition: StyleType.Transition,

  heatmapRadius: StyleType.Constant,
  heatmapRadiusTransition: StyleType.Transition,
  heatmapWeight: StyleType.Constant,
  heatmapIntensity: StyleType.Constant,
  heatmapIntensityTransition: StyleType.Transition,
  heatmapColor: StyleType.Color,
  heatmapOpacity: StyleType.Constant,
  heatmapOpacityTransition: StyleType.Transition,

  fillExtrusionOpacity: StyleType.Constant,
  fillExtrusionOpacityTransition: StyleType.Transition,
  fillExtrusionColor: StyleType.Color,
  fillExtrusionColorTransition: StyleType.Transition,
  fillExtrusionTranslate: StyleType.Translation,
  fillExtrusionTranslateTransition: StyleType.Transition,
  fillExtrusionTranslateAnchor: StyleType.Enum,
  fillExtrusionPattern: StyleType.Image,
  fillExtrusionPatternTransition: StyleType.Transition,
  fillExtrusionHeight: StyleType.Constant,
  fillExtrusionHeightTransition: StyleType.Transition,
  fillExtrusionBase: StyleType.Constant,
  fillExtrusionBaseTransition: StyleType.Transition,
  fillExtrusionVerticalGradient: StyleType.Constant,

  rasterOpacity: StyleType.Constant,
  rasterOpacityTransition: StyleType.Transition,
  rasterHueRotate: StyleType.Constant,
  rasterHueRotateTransition: StyleType.Transition,
  rasterBrightnessMin: StyleType.Constant,
  rasterBrightnessMinTransition: StyleType.Transition,
  rasterBrightnessMax: StyleType.Constant,
  rasterBrightnessMaxTransition: StyleType.Transition,
  rasterSaturation: StyleType.Constant,
  rasterSaturationTransition: StyleType.Transition,
  rasterContrast: StyleType.Constant,
  rasterContrastTransition: StyleType.Transition,
  rasterResampling: StyleType.Enum,
  rasterFadeDuration: StyleType.Constant,

  hillshadeIlluminationDirection: StyleType.Constant,
  hillshadeIlluminationAnchor: StyleType.Enum,
  hillshadeExaggeration: StyleType.Constant,
  hillshadeExaggerationTransition: StyleType.Transition,
  hillshadeShadowColor: StyleType.Color,
  hillshadeShadowColorTransition: StyleType.Transition,
  hillshadeHighlightColor: StyleType.Color,
  hillshadeHighlightColorTransition: StyleType.Transition,
  hillshadeAccentColor: StyleType.Color,
  hillshadeAccentColorTransition: StyleType.Transition,

  backgroundColor: StyleType.Color,
  backgroundColorTransition: StyleType.Transition,
  backgroundPattern: StyleType.Image,
  backgroundPatternTransition: StyleType.Transition,
  backgroundOpacity: StyleType.Constant,
  backgroundOpacityTransition: StyleType.Transition,

  anchor: StyleType.Enum,
  position: StyleType.Constant,
  positionTransition: StyleType.Transition,
  color: StyleType.Color,
  colorTransition: StyleType.Transition,
  intensity: StyleType.Constant,
  intensityTransition: StyleType.Transition,

  visibility: StyleType.Constant,
};

const STYLE_OVERRIDES = {
  // padding
  iconTextFitPadding: {
    iosType: "edgeinsets",
  },

  // offsets
  iconOffset: {
    iosType: "vector",
  },
  textOffset: {
    iosType: "vector",
  },
  lineOffset: {
    iosType: "vector",
  },

  // translates
  fillTranslate: {
    iosType: "vector",
  },
  lineTranslate: {
    iosType: "vector",
  },
  iconTranslate: {
    iosType: "vector",
  },
  textTranslate: {
    iosType: "vector",
  },
  circleTranslate: {
    iosType: "vector",
  },
  fillExtrusionTranslate: {
    iosType: "vector",
  },
};

export function getStylePropertyType(
  styleProperty: keyof typeof STYLE_OVERRIDES,
): string {
  if (!isAndroid() && STYLE_OVERRIDES[styleProperty]) {
    return STYLE_OVERRIDES[styleProperty].iosType;
  }

  if (STYLE_MAP[styleProperty]) {
    return STYLE_MAP[styleProperty];
  }

  throw new Error(`${styleProperty} is not a valid MapLibre layer style`);
}
