import { promises as fs } from "node:fs";
import path from "node:path";

import { autoGeneratedHeader } from "../styles/utils/autoGeneratedHeader";
import { PACKAGE_PATH, ROOT_PATH } from "../utils/pathes";

/**
 * Generates AndroidTextureMapViewNativeComponent.ts from
 * MapViewNativeComponent.ts template
 *
 * Can be removed once codegen supports imports:
 * https://github.com/facebook/react-native/issues/38769
 */
export async function generateAndroidTextureMapView() {
  const sourceFile = path.join(
    PACKAGE_PATH,
    "src",
    "components",
    "map",
    "MapViewNativeComponent.ts",
  );

  const targetFile = path.join(
    PACKAGE_PATH,
    "src",
    "components",
    "map",
    "AndroidTextureMapViewNativeComponent.ts",
  );

  console.log("Generating AndroidTextureMapViewNativeComponent.ts");

  const content = await fs.readFile(sourceFile, "utf8");

  const replacedContent = content.replace(
    /export default codegenNativeComponent<NativeProps>\(\n {2}"MLRNMapView",\n\) as HostComponent<NativeProps>;/,
    `export default codegenNativeComponent<NativeProps>(
  "MLRNAndroidTextureMapView",
  { excludedPlatforms: ["iOS"] },
) as HostComponent<NativeProps>;`,
  );

  if (replacedContent === content) {
    throw new Error(
      `Failed to generate AndroidTextureMapViewNativeComponent.ts`,
    );
  }

  const androidContent =
    `// ${autoGeneratedHeader.doNotModify}\n` +
    `// ${autoGeneratedHeader.generatedFrom(
      path.relative(ROOT_PATH, sourceFile),
    )}\n\n` +
    replacedContent;

  await fs.writeFile(targetFile, androidContent);
}
