import { promises as fs } from "node:fs";
import path from "node:path";

import { autoGeneratedHeader } from "../utils/TemplateHelpers";

/**
 * Generates AndroidTextureMapViewNativeComponent.ts from MapViewNativeComponent.ts template
 * Can be removed once codegen supports imports: https://github.com/facebook/react-native/issues/38769
 */
export async function generateAndroidTextureMapView() {
  const repositoryRoot = path.join(__dirname, "..", "..");

  const sourceFile = path.join(
    repositoryRoot,
    "src",
    "components",
    "map-view",
    "MapViewNativeComponent.ts",
  );

  const targetFile = path.join(
    repositoryRoot,
    "src",
    "components",
    "map-view",
    "AndroidTextureMapViewNativeComponent.ts",
  );

  console.log("Generating AndroidTextureMapViewNativeComponent.ts");

  const content = await fs.readFile(sourceFile, "utf8");

  const androidContent =
    `// ${autoGeneratedHeader.doNotModify}\n` +
    `// ${autoGeneratedHeader.generatedFrom(
      path.relative(repositoryRoot, sourceFile),
    )}\n\n` +
    content.replace(
      /export default codegenNativeComponent<NativeProps>\(\n {2}"MLRNMapView",\n\) as HostComponent<NativeProps>;/,
      `export default codegenNativeComponent<NativeProps>(
  "MLRNAndroidTextureMapView",
  { excludedPlatforms: ["iOS"] },
) as HostComponent<NativeProps>;`,
    );

  await fs.writeFile(targetFile, androidContent);

  console.log("✓ AndroidTextureMapViewNativeComponent.ts generated");
}
