import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  setup: [{ type: "autogenerated", dirName: "setup" }],
  guides: [{ type: "autogenerated", dirName: "guides" }],
  components: [{ type: "autogenerated", dirName: "components" }],
  modules: [{ type: "autogenerated", dirName: "modules" }],
};

export default sidebars;
