import type { Layer } from "../types/Layer";
import type { LayerProperty } from "../types/LayerProperty";
import { autoGeneratedHeader } from "../utils/autoGeneratedHeader";
import { pascalCase } from "../utils/pascalCase";

const LAYER_TYPES: Record<string, string> = {
  fill: "FillLayer",
  "fill-extrusion": "FillExtrusionLayer",
  line: "LineLayer",
  symbol: "SymbolLayer",
  circle: "CircleLayer",
  background: "BackgroundLayer",
  raster: "RasterLayer",
  heatmap: "HeatmapLayer",
  hillshade: "HillshadeLayer",
  light: "Light",
};

function androidInputType(type: string, value?: string): string {
  if (type === "array" && value) {
    return `${androidInputType(value)}[]`;
  }

  switch (type) {
    case "color":
      return "Integer";
    case "colorArray":
      return "String[]";
    case "boolean":
      return "Boolean";
    case "number":
      return "Float";
    case "numberArray":
      return "Float[]";
    default:
      return "String";
  }
}

function androidGetConfigType(androidType: string, prop: LayerProperty) {
  switch (androidType) {
    case "Integer":
      return "styleValue.getInt(VALUE_KEY)";
    case "Float":
      return "styleValue.getFloat(VALUE_KEY)";
    case "Boolean":
      return "styleValue.getBoolean(VALUE_KEY)";
    case "Float[]":
      return "styleValue.getFloatArray(VALUE_KEY)";
    case "String[]":
      return "styleValue.getStringArray(VALUE_KEY)";
    default:
      if (prop.image) {
        return "styleValue.getImageURI()";
      } else {
        return "styleValue.getString(VALUE_KEY)";
      }
  }
}

export function render(layers: Layer[], filePath: string): string {
  const layerMethods = layers
    .map((layer) => {
      const propCases = layer.properties
        .flatMap((prop) => {
          const cases: string[] = [];

          if (prop.image) {
            cases.push(`          case "${prop.name}":
            style.addImage(styleValue, new DownloadMapImageTask.OnAllImagesLoaded() {
                @Override
                public void onAllImagesLoaded() {
                    MLRNStyleFactory.set${pascalCase(prop.name)}(layer, styleValue);
                }
            });
            break;`);
          } else {
            cases.push(`            case "${prop.name}":
              MLRNStyleFactory.set${pascalCase(prop.name)}(layer, styleValue);
              break;`);
          }

          if (prop.transition) {
            cases.push(`          case "${prop.name}Transition":
            MLRNStyleFactory.set${pascalCase(prop.name)}Transition(layer, styleValue);
            break;`);
          }

          return cases;
        })
        .join("\n");

      return `    public static void set${pascalCase(layer.name)}LayerStyle(final ${LAYER_TYPES[layer.name as string]} layer, MLRNStyle style) {
      List<String> styleKeys = style.getAllStyleKeys();

      if (styleKeys.isEmpty()) {
        return;
      }

      for (String styleKey : styleKeys) {
        final MLRNStyleValue styleValue = style.getStyleValueForKey(styleKey);

        switch (styleKey) {
${propCases}
        }
      }
    }`;
    })
    .join("\n\n");

  const setterMethods = layers
    .flatMap((layer) =>
      layer.properties.flatMap((prop) => {
        const layerType = LAYER_TYPES[layer.name as string];
        const methods: string[] = [];

        let body: string;
        if (layer.name === "light" && prop.name === "position") {
          body = `      Float[] values = styleValue.getFloatArray(VALUE_KEY);
      layer.set${pascalCase(prop.name)}(Position.fromPosition(values[0], values[1], values[2]));`;
        } else if (layer.name === "light") {
          body = `      layer.set${pascalCase(prop.name)}(${androidGetConfigType(androidInputType(prop.type, prop.value), prop)});`;
        } else if (prop.name === "visibility") {
          body = `      layer.setProperties(PropertyFactory.visibility(styleValue.getString(VALUE_KEY)));`;
        } else if (prop.type === "resolvedImage") {
          body = `      if (styleValue.isExpression()) {
        if (styleValue.isImageStringValue()) {
          layer.setProperties(PropertyFactory.${prop.name}(styleValue.getImageStringValue()));
        } else {
          layer.setProperties(PropertyFactory.${prop.name}(styleValue.getExpression()));
        }
      } else {
        layer.setProperties(PropertyFactory.${prop.name}(${androidGetConfigType(androidInputType(prop.type, prop.value), prop)}));
      }`;
        } else {
          body = `      if (styleValue.isExpression()) {
        layer.setProperties(PropertyFactory.${prop.name}(styleValue.getExpression()));
      } else {
        layer.setProperties(PropertyFactory.${prop.name}(${androidGetConfigType(androidInputType(prop.type, prop.value), prop)}));
      }`;
        }

        methods.push(`    public static void set${pascalCase(prop.name)}(${layerType} layer, MLRNStyleValue styleValue) {
${body}
    }`);

        if (prop.transition) {
          methods.push(`    public static void set${pascalCase(prop.name)}Transition(${layerType} layer, MLRNStyleValue styleValue) {
      TransitionOptions transition = styleValue.getTransition();
      if (transition != null) {
        layer.set${pascalCase(prop.name)}Transition(transition);
      }
    }`);
        }

        return methods;
      }),
    )
    .join("\n\n");

  return `// ${autoGeneratedHeader.doNotModify}
// ${autoGeneratedHeader.generatedFrom(filePath)}

package org.maplibre.reactnative.components.layer.style;

import org.maplibre.android.style.layers.BackgroundLayer;
import org.maplibre.android.style.layers.CircleLayer;
import org.maplibre.android.style.layers.FillExtrusionLayer;
import org.maplibre.android.style.layers.FillLayer;
import org.maplibre.android.style.layers.LineLayer;
import org.maplibre.android.style.layers.PropertyFactory;
import org.maplibre.android.style.layers.RasterLayer;
import org.maplibre.android.style.layers.SymbolLayer;
import org.maplibre.android.style.layers.HeatmapLayer;
import org.maplibre.android.style.layers.HillshadeLayer;
import org.maplibre.android.style.layers.TransitionOptions;
import org.maplibre.android.style.light.Light;
import org.maplibre.android.style.light.Position;
import org.maplibre.reactnative.utils.DownloadMapImageTask;

import java.util.List;

public class MLRNStyleFactory {
    public static final String VALUE_KEY = "value";
    public static final String SHOULD_ADD_IMAGE_KEY = "shouldAddImage";

${layerMethods}

${setterMethods}
}
`;
}
