import type { LayerSpecification } from "@maplibre/maplibre-gl-style-spec";

import type { Layer } from "../types/Layer";
import type { LayerProperty } from "../types/LayerProperty";
import { autoGeneratedHeader } from "../utils/autoGeneratedHeader";
import { pascalCase } from "../utils/pascalCase";

const LAYER_TYPES: Record<LayerSpecification["type"] | "light", string> = {
  background: "BackgroundLayer",
  circle: "CircleLayer",
  "color-relief": "ColorReliefLayer",
  fill: "FillLayer",
  "fill-extrusion": "FillExtrusionLayer",
  heatmap: "HeatmapLayer",
  hillshade: "HillshadeLayer",
  line: "LineLayer",
  raster: "RasterLayer",
  symbol: "SymbolLayer",

  light: "Light",
};

function androidInputType(type: string, value?: string): string {
  if (type === "array" && value) {
    return `${androidInputType(value)}[]`;
  }

  switch (type) {
    case "color":
      return "Integer";
    case "colorArray":
      return "String[]";
    case "boolean":
      return "Boolean";
    case "number":
      return "Float";
    case "numberArray":
      return "Float[]";
    default:
      return "String";
  }
}

function androidGetConfigType(androidType: string, prop: LayerProperty) {
  switch (androidType) {
    case "Integer":
      return "styleValue.getInt(VALUE_KEY)";
    case "Float":
      return "styleValue.getFloat(VALUE_KEY)";
    case "Boolean":
      return "styleValue.getBoolean(VALUE_KEY)";
    case "Float[]":
      return "styleValue.getFloatArray(VALUE_KEY)";
    case "String[]":
      return "styleValue.getStringArray(VALUE_KEY)";
    default:
      if (prop.image) {
        return "styleValue.imageURI";
      } else {
        return "styleValue.getString(VALUE_KEY)";
      }
  }
}

export function render(layers: Layer[], filePath: string): string {
  const layerMethods = layers
    .map((layer) => {
      const propCases = layer.properties
        .flatMap((prop) => {
          const cases: string[] = [];

          if (prop.image) {
            cases.push(`                "${prop.name}" -> {
                    style.addImage(
                        styleValue,
                    ) { set${pascalCase(prop.name)}(layer, styleValue) }
                }`);
          } else {
            cases.push(`                "${prop.name}" -> {
                    set${pascalCase(prop.name)}(layer, styleValue)
                }`);
          }

          if (prop.transition) {
            cases.push(`                "${prop.name}Transition" -> {
                    set${pascalCase(prop.name)}Transition(layer, styleValue)
                }`);
          }

          return cases;
        })
        .join("\n\n");

      return `    fun set${pascalCase(layer.name)}LayerStyle(
        layer: ${LAYER_TYPES[layer.name]},
        style: MLRNStyle,
    ) {
        val styleKeys = style.allStyleKeys

        if (styleKeys.isEmpty()) {
            return
        }

        for (styleKey in styleKeys) {
            val styleValue = style.getStyleValueForKey(styleKey)

            when (styleKey) {
${propCases}
            }
        }
    }`;
    })
    .join("\n\n");

  const setterMethods = layers
    .flatMap((layer) =>
      layer.properties.flatMap((prop) => {
        const layerType = LAYER_TYPES[layer.name];
        const methods: string[] = [];

        let body: string;
        if (layer.name === "light" && prop.name === "position") {
          body = `        val values = styleValue.getFloatArray(VALUE_KEY)
        layer.position = Position.fromPosition(values[0]!!, values[1]!!, values[2]!!)`;
        } else if (layer.name === "light") {
          const androidType = androidInputType(prop.type, prop.value);
          const value = androidGetConfigType(androidType, prop);
          if (androidType === "Integer") {
            body = `        layer.set${pascalCase(prop.name)}(${value})`;
          } else {
            body = `        layer.${prop.name} = ${value}`;
          }
        } else if (prop.name === "visibility") {
          body = `        layer.setProperties(PropertyFactory.visibility(styleValue.getString(VALUE_KEY)))`;
        } else if (prop.type === "resolvedImage") {
          body = `        if (styleValue.isExpression()) {
            if (styleValue.isImageStringValue) {
                layer.setProperties(PropertyFactory.${prop.name}(styleValue.getImageStringValue()))
            } else {
                layer.setProperties(PropertyFactory.${prop.name}(styleValue.getExpression()))
            }
        } else {
            layer.setProperties(PropertyFactory.${prop.name}(${androidGetConfigType(androidInputType(prop.type, prop.value), prop)}))
        }`;
        } else {
          body = `        if (styleValue.isExpression()) {
            layer.setProperties(PropertyFactory.${prop.name}(styleValue.getExpression()))
        } else {
            layer.setProperties(PropertyFactory.${prop.name}(${androidGetConfigType(androidInputType(prop.type, prop.value), prop)}))
        }`;
        }

        methods.push(`    fun set${pascalCase(prop.name)}(
        layer: ${layerType},
        styleValue: MLRNStyleValue,
    ) {
${body}
    }`);

        if (prop.transition) {
          methods.push(`    fun set${pascalCase(prop.name)}Transition(
        layer: ${layerType},
        styleValue: MLRNStyleValue,
    ) {
        val transition = styleValue.transition
        if (transition != null) {
            layer.${prop.name}Transition = transition
        }
    }`);
        }

        return methods;
      }),
    )
    .join("\n\n");

  return `// ${autoGeneratedHeader.doNotModify}
// ${autoGeneratedHeader.generatedFrom(filePath)}
package org.maplibre.reactnative.components.layer.style

import org.maplibre.android.style.layers.BackgroundLayer
import org.maplibre.android.style.layers.CircleLayer
import org.maplibre.android.style.layers.FillExtrusionLayer
import org.maplibre.android.style.layers.FillLayer
import org.maplibre.android.style.layers.HeatmapLayer
import org.maplibre.android.style.layers.HillshadeLayer
import org.maplibre.android.style.layers.LineLayer
import org.maplibre.android.style.layers.PropertyFactory
import org.maplibre.android.style.layers.RasterLayer
import org.maplibre.android.style.layers.SymbolLayer
import org.maplibre.android.style.light.Light
import org.maplibre.android.style.light.Position

object MLRNStyleFactory {
    const val VALUE_KEY: String = "value"

${layerMethods}

${setterMethods}
}
`;
}
