name: Release

on:
  push:
    branches:
      - main
      - beta
      - alpha

jobs:
  review:
    name: Review
    uses: ./.github/workflows/review.yml

  release:
    name: Release
    needs: [review]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./package
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup

      - name: Audit Signatures
        run: |
          npm audit signatures

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn semantic-release
